### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by wobbals**
A description is provided in order to merge the merge.

### CODE REVIEW

**Comment by wobbals** [comment]
I have strong opinions about this.

**Comment by wobbals** [comment]
Can has webhook plz?

**Comment by wobbals** [comment]
merge this please

**Comment by wobbals** [comment]
merge this please

**Comment by tbdeploy** [comment]
I will not merge closed issues. I won't do it.

**Comment by wobbals** [comment]
merge this please

**Comment by tbdeploy** [comment]
Alright, I'm doing it. Check status at:

**Comment by wobbals** [comment]
merge this please

**Comment by tbdeploy** [comment]
Alright, I'm doing it. Check status at:

**Comment by wobbals** [comment]
Merge this please

**Comment by wobbals** [comment]
merge this please

**Comment by tbdeploy** [comment]
Alright, I'm doing it. Check status at: https://charles.tokbox.com/job/task-perform-pancake-merge/

**Comment by wobbals** [comment]
merge this please

**Comment by tbdeploy** [comment]
Alright, I'm doing it. Check status at: https://charles.tokbox.com/job/task-perform-pancake-merge/

**Pull request closed without merging**
